name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create .env file
        run: |
          touch .env
          echo PORT=${{ secrets.PORT }} >> .env
          echo DB_HOST=${{ secrets.DB_HOST }} >> .env
          echo NODE_ENV=production >> .env

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Deploy to Server
        uses: appleboy/ssh-action@v1.2.1
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd Bomberman-2.0-Backend
            git pull origin main
            cat <<EOF > .env
            PORT=${{ secrets.PORT }}
            DB_HOST=${{ secrets.DB_HOST }}
            NODE_ENV=production
            EOF
            npm install --production
            npm run build
            pm2 restart app
