name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create .env file
        run: |
          touch .env
          echo PORT=${{ secrets.PORT }} >> .env
          echo DB_HOST=${{ secrets.DB_HOST }} >> .env
          echo NODE_ENV=production >> .env

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Deploy to Server
        uses: appleboy/ssh-action@v1.2.1
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "Loading NVM..."
            export NVM_DIR="$HOME/.nvm"
            source "$NVM_DIR/nvm.sh"
            nvm use 22.14.0 

            cd Bomberman-2.0-Backend
            git pull https://${{ secrets.USERNAME }}:${{ secrets.TOKEN }}@github.com/${{ secrets.USERNAME }}/Bomberman-2.0-Backend.git main            

            echo "Updating environment variables..."
            cat <<EOF > .env
            PORT=${{ secrets.PORT }}
            DB_HOST=${{ secrets.DB_HOST }}
            NODE_ENV=production
            EOF

            echo "Cleaning old build..."
            rm -rf dist

            echo "Installing dependencies..."
            npm install --production

            echo "Building the application..."
            npm run build

            echo "Restarting application..."
            pm2 restart app
