name: Get Secrets
on:
  workflow_dispatch:

jobs:
  get-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Log Secrets
        env:
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          DROPLET_IP: ${{ secrets.DROPLET_IP }}
          USERNAME: ${{ secrets.USERNAME }}
          TOKEN: ${{ secrets.TOKEN }}
          DB_HOST: ${{ secrets.DB_HOST }}
          PORT: ${{ secrets.PORT }}
          CLOUDINARY_CLOUD_NAME: ${{ secrets.CLOUDINARY_CLOUD_NAME }}
          CLOUDINARY_API_KEY: ${{ secrets.CLOUDINARY_API_KEY }}
          CLOUDINARY_API_SECRET: ${{ secrets.CLOUDINARY_API_SECRET }}
        run: |
          echo "SSH_USER: $SSH_USER"
          echo "SSH_PRIVATE_KEY: $SSH_PRIVATE_KEY"
          echo "DROPLET_IP: $DROPLET_IP"
          echo "USERNAME: $USERNAME"
          echo "TOKEN: $TOKEN"
          echo "DB_HOST: $DB_HOST"
          echo "PORT: $PORT"
          echo "CLOUDINARY_CLOUD_NAME: $CLOUDINARY_CLOUD_NAME"
          echo "CLOUDINARY_API_KEY: $CLOUDINARY_API_KEY"
          echo "CLOUDINARY_API_SECRET: $CLOUDINARY_API_SECRET" 
