name: Get Secrets
on:
  workflow_dispatch:

jobs:
  get-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Log Secrets
        run: |
          echo "SSH_USER: $SSH_USER"
          echo "SSH_PRIVATE_KEY: $SSH_PRIVATE_KEY"
          echo "DROPLET_IP: $DROPLET_IP"
          echo "USERNAME: $USERNAME"
          echo "TOKEN: $TOKEN"
          echo "DB_HOST: $DB_HOST"
          echo "PORT: $PORT" 
